image: golang:latest

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  cache:
    paths:
      - .go/pkg/mod/

variables:
  OUTPUT_NAME: __bin__/$CI_PROJECT_NAME

stages:
  - build

build:
  stage: build
  script:
    - docker build -f app/Dockerfile -t dnsx2k/partymq:latest .
  artifacts:
    paths:
      - $OUTPUT_NAME
