name: Integration tests v2
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      options: --privileged
    steps:
      - name: Tests
        run: docker compose up
        with:
          file: docker-compose.yml