name: Integration tests v2
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Tests
        run: curl https://www.google.com
