name: Integration tests v2
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: docker:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: docker compose up -d
      - name: Test
        run: docker run --network partymq_some-development appropriate/curl -s --retry 10 --retry-connrefused http://localhost:8080/run

