name: Integration Tests
on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: docker compose -f tests/docker-compose.yml up -d
      - name: Trigger
        run: docker run --network=partymq-project_some-development appropriate/curl -s --retry 10 --retry-connrefused -X POST http://tests:8080/run > results.json
      - name: Verify
        run: ./tests/verify.sh

